[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    spa = "index.html"
  [plugins.inputs.postBuild]
      enable = true
      